version: '3.7'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=zorpia_auth
    ports:
      - "5432:5432"

  authentication:
    env_file:
      - .env
    build:
      context: ./backend/authentication

    depends_on:
      - db

  chatapp:
    env_file:
      - .env
    build:
      context: ./backend/chatapp

    command: 'python -u consumer.py'
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  userside:
    env_file:
      - .env
    build:
      context: ./backend/userside
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  frontend: