version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=zorpia_auth
    ports:
      - "5432:5432"


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  authentication:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend/authentication
      dockerfile: docker/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  # chatapp:
  #   env_file:
  #     - .env
  #   build:
  #     context: ./backend/chatapp

  #   command: 'python -u consumer.py'
  #   depends_on:
  #     - redis
  
  celery:
    build: 
      context: ./backend/authentication
      dockerfile: docker/celery/Dockerfile
    depends_on:
      - redis


  userside:
    env_file:
      - .env
    build:
      context: ./backend/userside
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  static:
  frontend: