version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=zorpia_auth
    ports:
      - "5432:5432"
  dbchat:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=zorpia_chat
    ports:
      - "5433:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


  authentication:
    image: bibin12/zorpia-backend:backend-authentication
    volumes:
      - static_authentication:/static
    env_file:
      - .env
    ports:
      - "8000:8000"

  daphne:
      image: bibin12/zorpia-backend:daphne
      command: bash -c "daphne -b 0.0.0.0 -p 8002 chatapp.asgi:application"
      ports:
        - "8002:8002"
      depends_on:
        - redis
        - chatapp

  chatapp:
    image: bibin12/zorpia-backend:backend-chatapp
    volumes:
      - static_chatapp:/static
    command: 'python -u consumer.py'
    depends_on:
      - redis
      - dbchat

  userside:
    image: bibin12/zorpia-backend:backend-userside
    volumes:
      - static_userside:/static
    env_file:
      - .env
    ports:
      - "8001:8001"


  celery:
    image: bibin12/zorpia-backend:backend-celery
    depends_on:
      - redis

  nginx:
    image: bibin12/zorpia-backend:backend-nginx
    volumes:
      - static_userside:/static_userside
      - static_authentication:/static_authentication
      - static_chatapp:/static_chatapp
    ports:
      - "80:80"


volumes:
  static_userside:
  static_authentication:
  static_chatapp:
