version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=zorpia_auth
    ports:
      - "5432:5432"
  dbchat:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bibin
      - POSTGRES_PASSWORD=bibin
      - POSTGRES_DB=zorpia_chat
    ports:
      - "5433:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


  authentication:
    volumes:
      - static_authentication:/static
    env_file:
      - .env
    build:
      context: ./authentication
      dockerfile: docker/django/Dockerfile
    ports:
      - "8000:8000"

  daphne:
      build:
        context: ./chatapp
      image: "chatapp:latest"
      command: bash -c "daphne -b 0.0.0.0 -p 8002 chatapp.asgi:application"
      ports:
        - "8002:8002"
      depends_on:
        - redis
        - chatapp

  chatapp:
    volumes:
      - static_chatapp:/static
    build:
      context: ./chatapp
    command: 'python -u consumer.py'
    depends_on:
      - redis
      - dbchat

  userside:
    volumes:
      - static_userside:/static
    build:
      context: ./userside
    ports:
      - "8001:8001"


  celery:
    build: 
      context: ./authentication
      dockerfile: docker/celery/Dockerfile
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_userside:/static_userside
      - static_authentication:/static_authentication
      - static_chatapp:/static_chatapp
    ports:
      - "80:80"


volumes:
  static_userside:
  static_authentication:
  static_chatapp:
