# Generated by Django 4.2.7 on 2024-01-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notificationroom_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='is_seen',
            new_name='seen',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='room',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='chatroom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='follower_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
