# Generated by Django 4.2.7 on 2024-01-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_is_seen_notifications_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='follower_username',
            new_name='by_user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='chatroom_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='seen',
        ),
    ]
