# Generated by Django 4.2.7 on 2024-01-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_follower_username_notifications_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='content',
        ),
    ]
