# Generated by Django 4.2.7 on 2024-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_notifications_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='post_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
