# Generated by Django 4.2.7 on 2024-01-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_notifications_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
