# Generated by Django 4.2.7 on 2024-01-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='m_type',
            field=models.CharField(blank=True),
        ),
    ]
