# Generated by Django 4.2.7 on 2024-01-29 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notifications_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationroom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
